/**
 * Commander action for `llmwiki init`.
 *
 * Generates a `llmwiki.config.ts` template in the current directory so the
 * user can implement their own LLM adapter and wire it to the wiki compiler.
 * Refuses to overwrite an existing config file.
 */

import { existsSync, writeFileSync } from "fs";
import path from "path";

/** Name of the config file generated by init. */
const CONFIG_FILENAME = "llmwiki.config.ts";

/** Template content written by `llmwiki init`. */
const CONFIG_TEMPLATE = `import { createWikiCompiler } from "llm-wiki-compiler";

// TODO: replace this stub with your real LLM implementation.
// You can use any LLM SDK — OpenAI, Anthropic, Ollama, etc.
const llm = {
  async complete(options: { system: string; prompt: string; maxTokens?: number }): Promise<string> {
    // Example using the OpenAI SDK:
    // const response = await openai.chat.completions.create({
    //   model: "gpt-4o",
    //   messages: [
    //     { role: "system", content: options.system },
    //     { role: "user", content: options.prompt },
    //   ],
    //   max_tokens: options.maxTokens,
    // });
    // return response.choices[0].message.content ?? "";

    throw new Error("TODO: implement your LLM complete() function");
  },
};

const wiki = createWikiCompiler({ llm });

// These are the library functions you can call programmatically:
//   await wiki.compile();
//   await wiki.query("What is X?");

export default wiki;
`;

/**
 * Run the init command — write llmwiki.config.ts to the current directory.
 * Exits early with a warning if the file already exists.
 * @param cwd - Directory to create the config in (defaults to process.cwd()).
 */
export default async function initCommand(cwd: string = process.cwd()): Promise<void> {
  const configPath = path.join(cwd, CONFIG_FILENAME);

  if (existsSync(configPath)) {
    console.warn(`\x1b[33m!\x1b[0m ${CONFIG_FILENAME} already exists — not overwriting.`);
    console.warn(`  Edit it directly to update your LLM adapter.`);
    return;
  }

  writeFileSync(configPath, CONFIG_TEMPLATE, "utf8");
  console.log(`\x1b[32m✓\x1b[0m Created ${CONFIG_FILENAME}`);
  console.log(`  Next steps:`);
  console.log(`    1. Open ${CONFIG_FILENAME} and implement the complete() function`);
  console.log(`    2. Run: llmwiki ingest <your-source-file>`);
  console.log(`    3. Run: npx ts-node llmwiki.config.ts  (or import it in your own script)`);
}
